### ISSUE TITLE
Drag and drop not working on Linux (KDE)

### ISSUE THREAD

**Issue by kefir500** [kefir500/apk-icon-editor#48]
### Issue:
Drag and drop not working on Linux (KDE).

### OS:
Kubuntu 16.04.

### Solution:
Use [`QMimeData::hasUrls()`](http://doc.qt.io/qt-5/qmimedata.html#hasUrls) instead of [`QMimeData::hasText()`](http://doc.qt.io/qt-5/qmimedata.html#hasText) in the `MainWindow::dropEvent()`.

### Tasks:
- [x] Commit the solution
- [x] Test on Linux (KDE)
- [x] Test on Linux (Gnome)
- [x] Test on Windows
- [x] Test on OS X

**Comment by kefir500** [comment]
Committed in c7a2f9e.
